### Imports e Definições de Constantes

In [1]:
import pandas as pd

In [2]:
FILEPATH = "../data/bronze/spotify_artist_streaming_2020_2025.csv"
SPOTIFY_TRACK_BASE = "https://open.spotify.com/track/"

data = pd.read_csv(FILEPATH, sep=",", encoding="utf-8")

### Análise Inicial

In [3]:
def initial_analysis(dataset):
    dataset.describe()
    display_dataset = dataset.head(200)
    display(display_dataset)

### Tratamento Básico

In [4]:
def remove_duplicates(dataset):
    dataset = dataset.dropna(subset=['track_id'])
    dataset = dataset.sort_values(by='release_date', ascending=True)
    dataset = dataset.drop_duplicates(subset=['track_id'], keep='first')
    return dataset

In [ ]:
def categorize_duration(dataset):
    bin_limit_length = [0, 1, 2, 3, 4, 5, 6, 9999]
    bin_labels_length = ['0-1 minutes', '1-2 minutes', '2-3 minutes', '3-4 minutes', '4-5 minutes', '5-6 minutes', '6+ minutes']

    dataset['duration_category'] = pd.cut(dataset['duration_minutes'], bins=bin_limit_length, labels=bin_labels_length, right=False)
    dataset = dataset.drop(columns=['duration_ms', 'duration_minutes'])
    return dataset

def remove_unnecessary_columns(dataset):
    columns_to_remove = ['key', 'mode', 'artist_track_count']
    dataset = dataset.drop(columns=columns_to_remove)
    return dataset

### Tabelas de Dimensão

In [ ]:
def dimensions(dataset):
    dim_genres = dataset['genre'].unique()
    dim_countries = dataset['country'].unique()
    dim_urls = [dataset['track_id'], dataset['track_id'].apply(lambda x: SPOTIFY_TRACK_BASE + str(x))]

    return dim_genres, dim_countries, dim_urls

In [11]:
def generate_files(dataset, genres, countries, urls):
    dataset.to_csv("../data/silver/spotify_artist_streaming_2020_2025_cleaned.csv", index=False)
    pd.DataFrame(genres).to_csv("../data/silver/spotify_artist_streaming_2020_2025_genres.csv", index=False)
    pd.DataFrame(countries).to_csv("../data/silver/spotify_artist_streaming_2020_2025_countries.csv", index=False)
    pd.DataFrame(urls).to_csv("../data/silver/spotify_artist_streaming_2020_2025_urls.csv", index=False)

In [10]:
if __name__ == "__main__":
    initial_analysis(data)
    data = remove_duplicates(data)
    data = categorize_duration(data)
    display_dataset = data.head(200)
    display(display_dataset)

,track_id,track_name,artist_name,album_name,release_date,genre,duration_ms,popularity,danceability,energy,...,loudness_category,key_name,mode_name,is_explicit_bool,release_quarter,is_weekend_release,log_stream_count,upbeat_score,artist_track_count,duration_category
25750,b83a1be3-7b31-4f11-a09f-f56fa6be304e,The Voices,Fibonacci,Glass Rivers,2020-01-01,Indie,282859,51,0.5383,0.3000,...,Moderate,D#,Major,False,Q1,False,11.3684,0.4029,39,4-5 minutes
3391,f5d7f416-ffdc-4f39-a90f-c2711dc581ba,Fading Echoes,Tundra,Archives,2020-01-01,Disco,176994,12,0.9495,0.8099,...,Loud,G,Major,True,Q1,False,7.7124,0.7855,25,2-3 minutes
42529,6b34c21b-9ca8-475c-aa7e-0850761b0cb9,Empty Roses,IsleEyre,Silent Flames,2020-01-01,Pop,197054,31,0.7265,0.8082,...,Loud,G,Major,False,Q1,False,10.4005,0.7301,5271,3-4 minutes
23142,c059dfa4-6c33-4913-a64d-008d5d957afc,The Rivers,SethStone,Cosmic Rain,2020-01-01,Metal,229133,3,0.1186,0.7481,...,Moderate,A,Major,False,Q1,False,7.2964,0.4046,1486,3-4 minutes
38008,c00a8d53-26fd-4eff-8f85-c2f8134699b4,Pulling Rain,The Brookss,Invisible Voices,2020-01-01,Classical,241421,65,0.0517,0.3572,...,Moderate,G#,Major,True,Q1,False,13.8162,0.1989,71,4-5 minutes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36425,6808b092-cf2d-4b59-b45c-5d7fdc4b53a9,Gardens,Knot Hart,The Burning Archives,2020-01-08,R&B,214526,54,0.7646,0.7291,...,Moderate,C,Major,False,Q1,False,12.2711,0.6583,12111,3-4 minutes
14112,694f48c8-3777-4229-a0d2-38422f29b9e8,Young Deep Doors,Knot Hart,Ghosts,2020-01-08,R&B,189349,24,0.6824,0.5483,...,Moderate,D#,Major,True,Q1,False,10.1331,0.5564,12111,3-4 minutes
8553,e2d7c9d8-1fb7-4f42-b0a6-bdb6215c1aad,Shadows,Sterling Zen,Invisible,2020-01-08,Pop,218301,8,0.6709,0.7330,...,Loud,F,Minor,False,Q1,False,8.5073,0.6785,2268,3-4 minutes
19667,388de8f8-a741-4e27-b6e9-9eedd283be3d,Bitter Demons,Knot Hart,Paper Roads,2020-01-08,R&B,307421,57,0.7767,0.3367,...,Moderate,D#,Major,False,Q1,False,13.2841,0.5031,12111,5-6 minutes
21833,8892081b-e1db-4f9d-8cf9-a8c6f01472a0,Dark Skies,The Crosss,Lights,2020-01-08,Jazz,193377,18,0.6938,0.3608,...,Moderate,B,Major,False,Q1,False,8.3018,0.4804,7,3-4 minutes

,track_id,track_name,artist_name,album_name,release_date,genre,duration_ms,popularity,danceability,energy,...,loudness_category,key_name,mode_name,is_explicit_bool,release_quarter,is_weekend_release,log_stream_count,upbeat_score,artist_track_count,duration_category
25750,b83a1be3-7b31-4f11-a09f-f56fa6be304e,The Voices,Fibonacci,Glass Rivers,2020-01-01,Indie,282859,51,0.5383,0.3000,...,Moderate,D#,Major,False,Q1,False,11.3684,0.4029,39,4-5 minutes
18269,2c4be940-7563-4476-9c32-02905ef6e9c8,Empty Sacred Roses,Hawk Theory,Cosmic Dreams,2020-01-01,Pop,246713,27,0.6271,0.6085,...,Loud,E,Major,True,Q1,False,9.6930,0.5688,492,4-5 minutes
33116,bc6ff3a1-9723-421b-bd77-98a45cb36e69,Winds,Knot Hart,Gentle Love,2020-01-01,Pop,244482,20,0.7584,0.4588,...,Moderate,F#,Major,False,Q1,False,7.6319,0.6095,12111,4-5 minutes
41324,7911dada-57b2-436c-9f0b-eafe092cd3b1,Islands,Hawk Sage,Crimson,2020-01-01,EDM,232725,13,0.8154,0.7135,...,Moderate,E,Minor,True,Q1,False,7.3218,0.6935,24,3-4 minutes
41272,8c847089-1a52-456e-a422-e3bce978e2e0,Drifting Roses,IsleEyre,Raw V,2020-01-01,Country,145535,63,0.5847,0.7024,...,Moderate,D,Minor,False,Q1,False,13.3240,0.6214,5271,2-3 minutes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45165,e6325f6b-2dcd-4eda-9e63-34390ed23f0a,Moving Bones,Isle Jay,Paper Winds,2020-01-08,EDM,166507,25,0.7742,0.4559,...,Moderate,A#,Major,True,Q1,False,9.8268,0.5531,241,2-3 minutes
27824,e2ec7ac3-e756-4a91-9fc7-43d64dc3bec6,Endless Pages,Luna Ink,Hollow III,2020-01-08,Hip-Hop,259981,57,0.7825,0.6182,...,Loud,G,Minor,True,Q1,False,13.4162,0.6825,577,4-5 minutes
45681,1a0c8508-561d-4af8-9063-a310df3ee277,Invisible Winds,Ethereal,Cosmic Stars,2020-01-08,Pop,115901,38,0.7340,0.6321,...,Moderate,E,Major,False,Q1,False,10.8180,0.6341,3232,1-2 minutes
30248,a88d4209-d6b3-4d5d-b366-d44be914d6a4,Memories,Knot Hart,Shattered Thunder,2020-01-08,R&B,169335,19,0.7549,0.6162,...,Moderate,B,Minor,False,Q1,False,9.3296,0.6311,12111,2-3 minutes
9247,7f0b6a9d-df08-4394-ad69-fa1073ab9d66,Gentle,Sterling Zen,Chains,2020-01-08,Folk,203418,46,0.3202,0.2803,...,Moderate,A,Major,True,Q1,False,11.5202,0.3012,2268,3-4 minutes

In [12]:
def run_cleanup(dataset):
    print("Starting data cleanup process...")
    data = remove_duplicates(dataset)
    print("Duplicates removed.")
    data = categorize_duration(dataset)
    print("Duration categorized.")
    genres, countries, urls = dimensions(dataset)
    print("Dimensions extracted.")
    
    generate_files(data, genres, countries, urls)
    print("Files generated successfully.")

In [ ]:
run_cleanup(data)